(define (domain starpz)
  (:requirements :strips)
  (:predicates 	(on ?disk1 ?disk2)
        	    (smaller ?disk1 ?disk2)
		        (clear ?disk)
                (isrod ?rod )
                (iscenter ?rod)
  )

  (:action MOVETOCENTER
   :parameters	(?disk ?source ?dest)
   :precondition	 
		(and    (isrod ?disk)
			    (iscenter ?dest)
			    (clear ?disk)
			    (on ?disk ?source)
			    (clear ?dest)
			    (smaller ?disk ?dest))
   :effect
		(and 	    (iscenter ?disk)
                            (not (isrod disk))
			    (isrod ?source)			    
			    (on ?disk ?dest)
			    (not (on ?disk ?source))
			    (not (clear ?dest))
			    (clear ?source))
  )
(:action MOVETOROD
   :parameters	(?disk ?source ?dest)
   :precondition	 
		(and    (iscenter ?disk)
			    (isrod ?dest)
			    (clear ?disk)
			    (on ?disk ?source)
			    (clear ?dest)
			    (smaller ?disk ?dest))
   :effect
		(and 	    (isrod disk)
			    (not (iscenter ?disk))
			    (iscenter source)
			    (on ?disk ?dest)
			    (not (on ?disk ?source))
			    (not (clear ?dest))
			    (clear ?source))
  )
)
